name: Release

on:
  push:
    tags:
      - '*'

permissions:
  contents: write

jobs:
  publish:
    name: Create Release
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version: stable

      - name: Install go-task
        uses: go-task/setup-task@v1

      - name: Install golangci-lint
        run: go install github.com/golangci/golangci-lint/v2/cmd/golangci-lint@v2.1.6

      - name: Run task check
        run: task check

      - name: Verify working tree clean
        run: git diff --exit-code

      - name: Test race conditions
        run: task test-race

      - name: Build
        run: task build

      - name: Create GitHub Release
        uses: softprops/action-gh-release@v2
        with:
          generate_release_notes: true
          files: ./compass
