version: '3.8'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
      args:
        # Update these to match your user's UID/GID if necessary
        USERNAME: vscode
        USER_UID: 1000
        USER_GID: 1000

    volumes:
      # Mount the workspace
      - ..:/workspace:cached

      # Mount Docker socket for Docker-in-Docker
      - /var/run/docker.sock:/var/run/docker.sock

    # Overrides default command so things don't shut down after the process ends
    command: sleep infinity

    # Use "forwardPorts" in **devcontainer.json** to forward an app port locally
    # (Adding the "ports" property to this file will not forward from a Codespace)

    # Set environment variables
    environment:
      - GO111MODULE=on
      - GOPROXY=https://proxy.golang.org,direct
      - GOSUMDB=sum.golang.org
      - CGO_ENABLED=1

    # Security options for debugging
    cap_add:
      - SYS_PTRACE
    security_opt:
      - seccomp:unconfined

    # Network mode
    network_mode: bridge

volumes:
  # Named volume for Go package cache (persists between container rebuilds)
  compass-go-pkg:
  compass-go-cache:
