when:
  event:
    - push
    - pull_request
  branch:
    - main

steps:
  - name: test
    image: golang:1.23
    commands:
      # Install go-task
      - go install github.com/go-task/task/v3/cmd/task@v3.43.3
      # Install golangci-lint
      - go install github.com/golangci/golangci-lint/v2/cmd/golangci-lint@v2.1.6
      # Download modules
      - go mod download
      # Run task check
      - task check
      # Verify working tree clean
      - git diff --exit-code
      # Test race conditions
      - task test-race
